require 'google_analytics_page_view_ranking/version'
require 'google_analytics_page_view_ranking/page_view'
require 'google_analytics_page_view_ranking/ranking'

module GoogleAnalyticsPageViewRanking
end
